name: Build and Package FLINT for Ubuntu with VCPKG

on:
  push:
    branches: 
      - main
      - master
      - develop
      - ubuntu_workflow
  pull_request:
    branches: 
      - main
      - master
      - develop
      - ubuntu_workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('Source/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Install and run dependencies
      run: |
        ./vcpkg/vcpkg install

    - name: Configure and build FLINT
      run: |
        mkdir -p Source/build
        cd Source/build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build .

    - name: Create executable package
      run: |
        cd Source/build
        zip -r moja-flint.zip .
        mv moja-flint.zip ../../moja-flint.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: moja-flint
        path: moja-flint.zip

    - name: Clean up after build
      run: |
        rm -rf Source/build
